### PR TITLE
move delete button to layout aside nav, similar to PFE

### PR DESCRIPTION
**Pull request by mcbouslog**

### CODE REVIEW

**Comment by mcbouslog** [comment]
tried Travis CI again, will look into why still not working, but I don't think should hold this PR up, please ignore failed checks.

**Comment by srallen** [comment]
I had actually put the delete button on the edit details page on purpose since it doesn't make sense to me why it's contained in a sidebar of navigation. Did you get feedback that this was confusing?

**Comment by mcbouslog** [comment]
Not that it was confusing where it was, just some inconsistencies between the current PFE project builder and this app were mentioned.

Your point that sidebar navigation shouldn't contain such an important button makes more sense though. I'd like to close this and will explain accordingly if comes up again in future demos.

**Comment by srallen** [comment]
Yeah, I would just tell them that the original project builder was never designed and we're putting in some effort to improve design, UI, and UX with the new iteration.

**Pull request closed without merging**
