### PR TITLE
About pages

### PR DESCRIPTION
**Pull request by srallen**
Initial setup for about page editor. 

TODO:
- [x] separate out into container/component structure
- [x] unit tests
- [x] Any fixes in response to zooniverse/Panoptes#2318

### CODE REVIEW

**Comment by srallen** [comment]
@wgranger would you be able to follow up on those to do items this week?

**Comment by wgranger** [comment]
Yeah. I assume you want me to tackle some of those issues. I can prob get cracking on some of them tomorrow.

**Comment by srallen** [comment]
Thanks!

**Comment by srallen** [comment]
This PR for markdownz should fix the errors throwing in the console: https://github.com/zooniverse/markdownz/pull/54

**Comment by wgranger** [comment]
The AboutContainer still had the old function names bound, so that bug fix was made with the most recent commit. Bug still exists on the url key.

**Comment by srallen** [comment]
@mcbouslog I still don't quite have working integration tests as I'd like, but if you go to a currently working org's about editor page, it all seems to work now. 

(as an aside, I actually couldn't delete the broken orgs via postman because I need a etag from the resource for the If-Match header, so I'll just follow up on that early next week)

**Comment by mcbouslog** [comment]
Closes #5

**Pull request merged**
