### PR TITLE
[Security] Build with node 16

### PR DESCRIPTION
**Pull request by eatyourgreens**
- Upgrade the builds, and Dockerfile, to node 16/npm 8.
- Upgrade `node-sass` to 7.0.0

Staging branch URL: https://pr-262.lab-preview.zooniverse.org/

# Review Checklist

- [ ] Does it work in all major browsers: Firefox, Chrome, Edge, Safari?
- [ ] Can you `rm -rf node_modules/ && npm install` and app works as expected?
- [ ] Are the tests passing locally and on Travis?

### CODE REVIEW

**Comment by eatyourgreens** [comment]
`node-sass` 7 requires [`sass-loader` 12.4.0](https://github.com/webpack-contrib/sass-loader/blob/master/CHANGELOG.md#1240-2021-12-07), which in turn requires Webpack 5.

Looking through the source, this project doesn't use Sass, so I'm going to take the path of least resistance and remove `sass-loader`.

**Comment by eatyourgreens** [comment]
My bad. Grommet uses Sass.
https://github.com/zooniverse/pfe-lab/blob/2f097d8093983488492d49ed20de9b58815b0bd2/src/index.jsx#L17

`node-sass` prior to 7 allows untrusted code to be installed and run during a build. We should fix this.

**Comment by mcbouslog** [comment]
I think upgrading to webpack v5 will be easier than upgrading to grommet v2, so I'll initially focus on upgrading to webpack v5. If I'm understanding correctly that'll allow an update to node-sass v7 (which includes the security fix).

**Comment by mcbouslog** [comment]
#264 updated build to node 16

**Pull request closed without merging**
