### PR TITLE
Update to react 16

### PR DESCRIPTION
**Pull request by srallen**
Let's update to React 16 and Enzyme. This is a first step to update to Grommet v2 and then be able to drop the old ZRC.

### CODE REVIEW

**Comment by srallen** [comment]
Can be tested: https://update-react.lab-preview.zooniverse.org/

Everything seems to work but the search to add users as collaborators or the search to link projects due to CORS errors. I'm not sure if this preexisting for staging.

**Review by mcbouslog — APPROVED** [review]
LGTM. Was able to create new org and edit/update it, also edit old testing orgs. Tests pass.

It's broken, not from this PR, but the project and collab add functionality works if once you make a selection it won't appear as selected, but if click Add it will add the project or collab to the org.

**Comment by mcbouslog** [comment]
Deployed to staging site - https://master.lab-preview.zooniverse.org/organizations

**Comment by srallen** [comment]
@mcbouslog I think staging looks ok to me. Let's plan on production deployment early next week?

**Comment by mcbouslog** [comment]
@srallen - my apologies, production (https://lab.zooniverse.org/) already includes the merge I made, I had forgotten we have auto-deploy for `master` merges recently setup. I'm working on updating the `README`, PR template, and `.travis.yml` accordingly.

**Pull request merged**
