### PR TITLE
Adds Deploy Staging Branch github action

### PR DESCRIPTION
**Pull request by zwolf**
Staging branch URL: https://pr-{NUMBER}.lab-preview.zooniverse.org/

^^^ we'll see, won't we? :D

### CODE REVIEW

**Comment by zwolf** [comment]
success: https://pr-231.lab-preview.zooniverse.org/

**Review by srallen — APPROVED** [review]
:shipit: This is really neat.

**Comment by srallen** [comment]
Actually, that URL is still S3? It's on Azure Blob storage, but we'll need the azure subdomain to check this still.

**Comment by zwolf** [comment]
correct, but you can use https://pr-231.lab-preview.azure.zooniverse.org if you don't mind living dangerously 😎

**Pull request merged**
